import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import randomLink from "../components/random";
import useWordCloud from "../components/text";
import useSWR from "swr";

export default function Home() {
  const fetcher = (url) => fetch(url).then((r) => r.json());
  const { data } = useSWR("/api/spotify", fetcher);

  useWordCloud();
  return (
    <>
      <Head>
        <title>Aihime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="HandheldFriendly" content="true" />
        <meta
          name="viewport"
          content="width=device-width, maximum-scale=1.0, user-scalable=yes"
        />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎀</text></svg>"
        />
      </Head>

      <div>
        <canvas id="c"></canvas>

        <div className="vertical-heading-2 center fade-in">
          <a style={{ fontSize: "5rem" }}>生きろ。</a>
        </div>

        <span>
          <Link style={{ lineHeight: "30px" }} href="/about">
            About
          </Link>
          <br />
          Made with ❤️ for You 🎀
        </span>
        <a
          className="a"
          href={
            data?.isPlaying
              ? data.songUrl
              : "/random"
          }
        >
          <section className="content_section">
            <div className="content_box">
              <img
                className="right_img"
                src={
                  data?.isPlaying
                    ? data?.albumImageUrl
                    : "https://media.tenor.com/AHISycRzhy0AAAAi/pjsekai-project-sekai.gif"
                }
                alt={data?.isPlaying ? data?.album : "mijuki"}
              ></img>
              <div className="title_text">
                <p className="info_title">
                  {data?.isPlaying
                    ? data.title
                    : "Well i'm not listening anything atm."}
                </p>
                <p className="info_sub">
                  {data?.isPlaying ? data.artist : "hi! (pwease click me!)"}
                </p>
              </div>
            </div>
          </section>
        </a>
      </div>
    </>
  );
}
